[package]
name = "masters_thesis"
version = "0.1.0"
authors = ["Sebastian Ossinger <sebastian.ossinger@mail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
